### ISSUE TITLE
stl files nyquist

### ISSUE THREAD

**Issue by pixelcatwave** [jeffeb3/jeffeb3#1]
How can i contact you? I wanted to ask if you had any other way to export the 3d files for the nyquist case that isn't stl or might work with fusion 360. I wanted to make it a higher profile and adjust the lip around the keys. Thanks!! https://github.com/jeffeb3/nyquist-case/blob/master/jeffeb3_case/README.md

**Comment by jeffeb3** [comment]
I updated the issue in the keebio repo.
